export const studioRegistrationKeys = [
  "email_address",
  "name",
  "studio_name",
  "studio_booking_address",
  "timezone",
  "password",
  "studio_password_requirements",
  "studio_register_continue",
  "studio_create_account",
  "studio_invite_owner",
  "studio_registration_sent",
  "studio_registration_complete",
  "studio_registration_invalid",
  "studio_slug_unavailable",
  "request_is_expired",
  "unexpected_error_try_again",
  "bad_request_error",
  "forbidden_error",
  "too_many_requests",
  "home_login",
  "studio_choose_availability",
  "studio_confirm_password",
  "studio_password_mismatch",
] as const;
